use_frameworks!

target 'JXKit_Example' do

    pod 'JXKit', :path => '~/Desktop/GitHub/JXKit/JXKit.podspec'
#    pod 'JXKit', '0.1.34'

  target 'JXKit_Tests' do
    inherit! :search_paths

    
  end
end
